server:
  port: 7070
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/hotel-room-bookings?createDatabaseIfNotExist=true
    username: root
    password: Emami@4321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
stripe:
  key: sk_test_51OAoRtSGoRmh8NxfwgLCKRVsX9tcAm0lcAQDjfRjyJgNR7CVvMevmQ2qJMNFFbAEgHi8bGqbxk5ILRxvLJv8Ooha00Jdt3EJEO
