server:
  port: 6060
spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: rakeshsur72@gmail.com
    password: uhan ymef opzt kdrr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
